# This file instructs Redocly's linter to ignore the rules contained for specific parts of your API.
# See https://redoc.ly/docs/cli/ for more information.
openapi.yaml:
  no-empty-servers:
    - '#/servers'
  operation-4xx-response:
    - '#/paths/~1health/get/responses'
  spec:
    - '#/components/schemas/Track/properties/metadata/nullable'
    - '#/components/schemas/PeerMetadata/nullable'
