version: "3"

x-jellyfish-template: &jellyfish-template
  build: .
  environment: &jellyfish-environment
    JF_SERVER_API_TOKEN: "development"
    JF_DIST_ENABLED: "true"
    JF_DIST_STRATEGY_NAME: "DNS"
  restart: on-failure

services:
  test:
    image: membraneframeworklabs/docker_membrane:latest
    command:
      - sh
      - -c
      - |
        cd app/ 
        mix deps.get 
        MIX_ENV=ci mix test --only cluster
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    depends_on:
      - app1
      - app2

  app1:
    <<: *jellyfish-template
    environment:
      <<: *jellyfish-environment
      JF_HOST: "localhost:4001"
      JF_PORT: 4001
      JF_DIST_QUERY: app.dns-network
    ports:
      - 4001:4001
    networks:
      default:
        aliases:
          - app.dns-network

  app2:
    <<: *jellyfish-template
    environment:
      <<: *jellyfish-environment
      JF_HOST: "localhost:4002"
      JF_PORT: 4002
      JF_DIST_QUERY: app.dns-network
    ports:
      - 4002:4002
    networks:
      default:
        aliases:
          - app.dns-network
