version: "3"

x-jellyfish-template: &jellyfish-template
  build: .
  environment: &jellyfish-environment
    ERLANG_COOKIE: "panuozzo-pollo-e-pancetta"
    JF_SERVER_API_TOKEN: "development"
    JF_HOST: "localhost"
    JF_NODES: "app@app1 app@app2"
  networks:
    - net1
  restart: on-failure

services:
  test:
    image: membraneframeworklabs/docker_membrane
    command:
      - sh
      - -c
      - |
        cd app/ 
        mix deps.get 
        MIX_ENV=ci mix test --only cluster
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    networks:
      - net1
    depends_on:
      - app1
      - app2

  app1:
    <<: *jellyfish-template
    environment:
      <<: *jellyfish-environment
      RELEASE_NODE: app@app1
      NODE_NAME: app@app1
      JF_PORT: 4001
    ports:
      - 4001:4001

  app2:
    <<: *jellyfish-template
    environment:
      <<: *jellyfish-environment
      RELEASE_NODE: app@app2
      NODE_NAME: app@app2
      JF_PORT: 4002
    ports:
      - 4002:4002

networks:
  net1:
    driver: bridge
