version: "3"

x-fishjam-template: &fishjam-template
  build:
    context: .
    args:
      - MIX_ENV=test
  environment: &fishjam-environment
    FJ_SERVER_API_TOKEN: "development"
    FJ_DIST_ENABLED: "true"
    FJ_DIST_MODE: "name"
    FJ_DIST_STRATEGY_NAME: "DNS"
    MIX_ENV: "test"
    FJ_FEATURE_FLAG_REQUEST_ROUTING_ENABLED: "true"
    FJ_COMPONENTS_USED: "hls file"
    FJ_SECRET_KEY_BASE: "secret"
  volumes:
    - ./test/fixtures:/app/fishjam_resources/file_component_sources
  restart: on-failure
  healthcheck:
    interval: 1s
    timeout: 10s
    retries: 20

services:
  test:
    build:
      context: .
      target: build
      args:
        - MIX_ENV=test_cluster
    command:
      - sh
      - -c
      - mix test --only cluster
    volumes:
      - ./test:/app/test
    depends_on:
      app1:
        condition: service_healthy
      app2:
        condition: service_healthy

  app1:
    <<: *fishjam-template
    environment:
      <<: *fishjam-environment
      FJ_HOST: "localhost:4001"
      FJ_PORT: 4001
      FJ_DIST_QUERY: app.dns-network
    ports:
      - 4001:4001
    networks:
      default:
        aliases:
          - app.dns-network

  app2:
    <<: *fishjam-template
    environment:
      <<: *fishjam-environment
      FJ_HOST: "localhost:4002"
      FJ_PORT: 4002
      FJ_DIST_QUERY: app.dns-network
    ports:
      - 4002:4002
    networks:
      default:
        aliases:
          - app.dns-network
