version: "3"

x-jellyfish-template: &jellyfish-template
  build: .
  environment: &jellyfish-environment
    JF_SERVER_API_TOKEN: "development"
    JF_DIST_ENABLED: "true"
    JF_DIST_MODE: "sname"
    JF_DIST_NODES: "app@app1 app@app2"
  restart: on-failure

services:
  test:
    image: membraneframeworklabs/docker_membrane
    command:
      - sh
      - -c
      - |
        cd app/ 
        mix deps.get 
        MIX_ENV=ci mix test --only cluster
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    depends_on:
      - app1
      - app2

  app1:
    <<: *jellyfish-template
    environment:
      <<: *jellyfish-environment
      JF_HOST: "localhost:4001"
      JF_PORT: 4001
      JF_DIST_NODE_NAME: app@app1
    ports:
      - 4001:4001

  app2:
    <<: *jellyfish-template
    environment:
      <<: *jellyfish-environment
      JF_HOST: "localhost:4002"
      JF_PORT: 4002
      JF_DIST_NODE_NAME: app@app2
    ports:
      - 4002:4002
