version: "3"

x-fishjam-template: &fishjam-template
  build: .
  environment: &fishjam-environment
    FJ_SERVER_API_TOKEN: "development"
    FJ_DIST_ENABLED: "true"
    FJ_DIST_NODES: "app@app1 app@app2"
  restart: on-failure

services:
  test:
    image: membraneframeworklabs/docker_membrane:latest
    command:
      - sh
      - -c
      - |
        cd app/ 
        mix deps.get 
        MIX_ENV=test_cluster mix test --only cluster
    volumes:
      - .:/app
      - /app/_build
      - /app/deps
    depends_on:
      - app1
      - app2

  app1:
    <<: *fishjam-template
    environment:
      <<: *fishjam-environment
      FJ_HOST: "localhost:4001"
      FJ_PORT: 4001
      FJ_DIST_NODE_NAME: app@app1
    ports:
      - 4001:4001

  app2:
    <<: *fishjam-template
    environment:
      <<: *fishjam-environment
      FJ_HOST: "localhost:4002"
      FJ_PORT: 4002
      FJ_DIST_NODE_NAME: app@app2
    ports:
      - 4002:4002
