# fly.toml file generated for jellyfish-media-server on 2023-04-13T16:32:52+02:00

app = "jellyfish-media-server"
kill_signal = "SIGTERM"
kill_timeout = 5
primary_region = "waw"
processes = []

[env]
  INTEGRATED_TCP_TURN_PORT = "49999"
  INTEGRATED_TURN_IP = "168.220.83.55"
  INTEGRATED_TURN_PORT_RANGE = "50000-59999"
  PORT = "4000"
  VIRTUAL_HOST = "jellyfish-media-server.fly.dev"
  WEBRTC_USED = "true"

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 1000
    soft_limit = 1000
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  internal_port = 50000
  protocol = "udp"

  [[services.ports]]
    port = 50000
