version: 2.1
orbs:
  elixir: membraneframework/elixir@1
  codecov: codecov/codecov@3.2.4

executors:
 machine_executor_amd64:
   machine:
     image: ubuntu-2204:2022.04.2
   environment:
     architecture: "amd64"
     platform: "linux/amd64"

jobs:
  test_load_balancing:
    executor: machine_executor_amd64
    steps:
      - checkout
      - run: docker compose run test
    
  test:
    docker:
      - image: membraneframeworklabs/docker_membrane:latest
        environment:
          MIX_ENV: test

    steps:
      - checkout
      - run: mix deps.get
      - run: mix coveralls.json --warnings-as-errors
      - codecov/upload

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          cache-version: 3
      - test
      - test_load_balancing
      - elixir/lint:
          cache-version: 3
          docs: false
