version: 2.1
orbs:
  elixir: membraneframework/elixir@1
  codecov: codecov/codecov@3.2.4

jobs:
  test:
    docker:
      - image: membraneframeworklabs/docker_membrane:latest
        environment:
          MIX_ENV: test

    steps:
      - checkout
      - run: mix deps.get
      - run: mix coveralls.json --warnings-as-errors
      - codecov/upload

workflows:
  version: 2
  build:
    jobs:
      - elixir/build_test:
          cache-version: 2
      - test
      - elixir/lint:
          cache-version: 2
          docs: false
