{
 "title": "Jellyfishes dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(jellyfish_rooms,instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 13, "w": 8, "x": 0, "y": 0 },
   "options": {
    "content": "This is Jellyfish dashboard\n\n![Text](https://avatars.githubusercontent.com/u/119447297?s=400&u=f714adece660ae05d4b177d1d4e7d7886aa4e9d5&v=4)"
   }
  },
  {
   "title": "Jellyfish news",
   "type": "news",
   "description": "Panel for RSS news from our organization.",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 0 }
  },
  { "title": "Rooms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Current number of rooms",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jellyfish_rooms{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rooms number",
   "type": "timeseries",
   "description": "Present the current number of rooms by jellyfish instance.",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(jellyfish_rooms{instance=~\"$instance\"}) by(instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Ingress & Egress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Ingress throughput ($instance)",
   "type": "timeseries",
   "description": "Ingress throughput from each of the jellyfish instances",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "jellyfish_traffic_ingress_throughput_bytes_per_second{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Egress throughput ($instance)",
   "type": "timeseries",
   "description": "Egress throughput from each of the jellyfish instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "jellyfish_traffic_egress_throughput_bytes_per_second{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Ingress and Egress throughput ($instance)",
   "type": "timeseries",
   "description": "Ingress and Egress throughput from each of the jellyfish instances",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "jellyfish_traffic_ingress_throughput_bytes_per_second{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} ingress"
    },
    {
     "expr": "jellyfish_traffic_egress_throughput_bytes_per_second{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} egress"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "VM memory ($instance)",
   "type": "timeseries",
   "description": "VM usage from each of the jellyfish instances",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "vm_memory_total_bytes{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}