name: Enforce PR policy

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

jobs:
  check-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Check PR
        run: |
          if [[ "${{ github.base_ref }}" == "main" ]] && ! [[ "${{ github.head_ref }}" =~ ^dev$|^fix/ ]]; then
            echo 'PRs to branch `main` can only come from branch `dev` or any branch prefixed with `fix/`'
            exit 1
          fi
